CREATE TABLE "INGREDIENTS" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255),
    "AMOUNT" DOUBLE NOT NULL,
    "UNIT" VARCHAR(255),
    "RECIPEID" INTEGER NOT NULL
);

CREATE TABLE "RECIPES" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255),
    "TYPE" INT,
    "CATEGORY" INT,
    "COOKINGTIME" INT NOT NULL,
    "NUMPORTIONS" INT NOT NULL,
    "INSTRUCTIONS" VARCHAR(255)
);
