CREATE TABLE "RECIPES" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255),
    "TYPE" INTEGER NOT NULL,
    "CATEGORY" INTEGER NOT NULL,
    "COOKINGTIME" INTEGER NOT NULL,
    "NUMPORTIONS" INTEGER NOT NULL,
    "INSTRUCTIONS" VARCHAR(255)
);

CREATE TABLE "INGREDIENTS" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255),
    "AMOUNT" DOUBLE,
    "UNIT" VARCHAR(255),
    "RECIPEID" INTEGER NOT NULL
);