/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.muni.pv168.gui;

import fi.muni.pv168.IngredientManagerImpl;
import fi.muni.pv168.RecipeManagerImpl;
import fi.muni.pv168.Recipebook;
import fi.muni.pv168.RecipebookImpl;
import java.awt.Dialog;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.DataSource;
import org.apache.commons.dbcp.BasicDataSource;

/**
 *
 * @author mulan
 */
public class RecipebookListJFrame extends javax.swing.JFrame {

    private Recipebook recipebook;
    
    private RecipeForm recipeForm;
    
    private IngredientForm ingredientForm;
    
    /**
     * Creates new form RecipebookListJFrame
     * 
     * 
     */
    private Logger logger = Logger.getLogger(RecipebookListJFrame.class.getName());
    
    private static BasicDataSource prepareDataSource() throws SQLException {
        BasicDataSource ds = new BasicDataSource();
        ds.setUrl("jdbc:derby:memory:recipebook-test;create=true");
        return ds;
    }
    
    public RecipebookListJFrame() {
        
        recipeForm = new RecipeForm();
        
        ingredientForm = new IngredientForm();
        
        DataSource ds = null;
        try {
            ds = prepareDataSource();
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, "Internal database cannot be initialized exiting", ex);
            System.exit(1);
        }
        
        this.recipebook = new RecipebookImpl(new IngredientManagerImpl(ds), new RecipeManagerImpl(ds));
        logger.log(Level.INFO, "Managers initialized");
        
         String createTableSQL1 = "CREATE TABLE INGREDIENTS("
                + "ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY, "
                + "NAME VARCHAR(255), "
                + "AMOUNT DOUBLE, "
                + "UNIT VARCHAR(255), "
                + "RECIPEID INTEGER NOT NULL "
                + ")";
        String createTableSQL2 = "CREATE TABLE RECIPES("
                + "ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY, "
                + "NAME VARCHAR(255), "
                + "TYPE INT, "
                + "CATEGORY INT, "
                + "COOKINGTIME INT, "
                + "NUMPORTIONS INT, "
                + "INSTRUCTIONS VARCHAR(255)"
                + ")";
        
        Connection con;
        try {
            con = ds.getConnection();
            con.setAutoCommit(false);
            PreparedStatement query = con.prepareStatement(createTableSQL1);
            query.executeUpdate();
            query = con.prepareStatement(createTableSQL2);
            query.executeUpdate();
            con.commit();
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, "Tables could not be inserted into internal database, exiting", ex);
            System.exit(1);
        }
        
        logger.log(Level.INFO, "Tables inserted into internal database, continuing happily");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RecipeList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        IngredientList = new javax.swing.JList();
        RecipeTextLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        RecipeNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RecipeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        RecipeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecipeListClicked(evt);
            }
        });
        jScrollPane1.setViewportView(RecipeList);

        IngredientList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        IngredientList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngredientListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(IngredientList);

        RecipeTextLabel.setText("jLabel1");

        jLabel2.setText("Ingredients");

        jButton1.setText("NewRecipe");
        jButton1.setName("NewRecipe"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewRecipeButtonClicked(evt);
            }
        });

        jButton2.setText("EditRecipe");
        jButton2.setName("EditRecipe"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditRecipeButtonClicked(evt);
            }
        });

        jButton3.setText("RemoveRecipe");
        jButton3.setName("RemoveRecipe"); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveRecipeButtonClicked(evt);
            }
        });

        jButton4.setText("AddIngredient");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddIngredientButtonClicked(evt);
            }
        });

        jButton5.setText("EditIngredient");
        jButton5.setToolTipText("");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditIngredientButtonClicked(evt);
            }
        });

        jButton6.setText("RemoveIngredient");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveIngredientButtonClicked(evt);
            }
        });

        RecipeNameLabel.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RecipeTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RecipeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RecipeNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RecipeTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewRecipeButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewRecipeButtonClicked
        logger.log(Level.INFO, "NewRecipeButton");
        recipeForm.show();
    }//GEN-LAST:event_NewRecipeButtonClicked

    private void EditRecipeButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditRecipeButtonClicked
        logger.log(Level.INFO, "EditRecipeButton");
        recipeForm.show();
    }//GEN-LAST:event_EditRecipeButtonClicked

    private void RemoveRecipeButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveRecipeButtonClicked
        logger.log(Level.INFO, "RemoveRecipeButton");
    }//GEN-LAST:event_RemoveRecipeButtonClicked

    private void AddIngredientButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddIngredientButtonClicked
        logger.log(Level.INFO, "AddIngredientButton");
        this.disable();
        ingredientForm.show();
        this.enable();
    }//GEN-LAST:event_AddIngredientButtonClicked

    private void EditIngredientButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditIngredientButtonClicked
         logger.log(Level.INFO, "EditIngredientButton");
         ingredientForm.show();
    }//GEN-LAST:event_EditIngredientButtonClicked

    private void RemoveIngredientButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveIngredientButtonClicked
         logger.log(Level.INFO, "RemoveIngredientButton");
    }//GEN-LAST:event_RemoveIngredientButtonClicked

    private void RecipeListClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecipeListClicked
        logger.log(Level.INFO, "RecileList clicked");
    }//GEN-LAST:event_RecipeListClicked

    private void IngredientListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngredientListMouseClicked
        logger.log(Level.INFO, "IngredientList clicked");
    }//GEN-LAST:event_IngredientListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipebookListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipebookListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipebookListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipebookListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipebookListJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList IngredientList;
    private javax.swing.JList RecipeList;
    private javax.swing.JLabel RecipeNameLabel;
    private javax.swing.JLabel RecipeTextLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
